version: '3'

services:
  nginx:
    build: 
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - .:/var/www/html
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  
 